name: GitHub Daily Report

on:
  workflow_dispatch:  # 仅手动触发

jobs:
  daily:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
      REPORT_REPOS: ${{ secrets.REPORT_REPOS }}
      API_KEY: ${{ secrets.API_KEY }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      API_MODEL: ${{ secrets.API_MODEL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run daily report
        run: node index.js daily

      - name: Check if data.json changed
        id: check_changes
        run: |
          git diff --quiet data.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push data.json
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "chore: update data.json [daily]"
          git push