# .github/workflows/github-monitor.yml
name: GitHub Monitor

on:
  schedule:
    # 每天 UTC 1:00 = 北京时间 9:00
    - cron: "0 1 * * *"
    # 每周三 UTC 12:00 = 北京时间 20:00
    - cron: "0 12 * * 3"

jobs:
  monitor:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
      REPORT_REPOS: ${{ secrets.REPORT_REPOS }}
      API_KEY: ${{ secrets.API_KEY }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      API_MODEL: ${{ secrets.API_MODEL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Determine task type
        id: set-task
        run: |
          if [ "$(date +%u)" -eq 3 ] && [ "$(date +%H)" -eq 12 ]; then
            echo "type=analysis" >> $GITHUB_OUTPUT
          else
            echo "type=daily" >> $GITHUB_OUTPUT
          fi

      - name: Run monitor script
        run: node index.js ${{ steps.set-task.outputs.type }}

      - name: Check if data.json changed
        id: check_changes
        run: |
          git diff --quiet data.json || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push data.json
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "chore: update data.json [${{ steps.set-task.outputs.type }}]"
          git push

